// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEY3MY4Ngof7ZFWLw4vGbheba44knpDjs',
    appId: '1:157785319634:web:85c72eefdb77154868e50b',
    messagingSenderId: '157785319634',
    projectId: 'marriage-app-71ea3',
    authDomain: 'marriage-app-71ea3.firebaseapp.com',
    storageBucket: 'marriage-app-71ea3.firebasestorage.app',
    measurementId: 'G-CMD64FNWHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZBY2qg6jku4moqK_vEZDUQkCDL9CLo0',
    appId: '1:157785319634:android:2d0e478133ca998c68e50b',
    messagingSenderId: '157785319634',
    projectId: 'marriage-app-71ea3',
    storageBucket: 'marriage-app-71ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZb0b2WNzSlGv9otaME6HyK1rgMzEp48',
    appId: '1:157785319634:ios:8b876ec55092e91a68e50b',
    messagingSenderId: '157785319634',
    projectId: 'marriage-app-71ea3',
    storageBucket: 'marriage-app-71ea3.firebasestorage.app',
    iosBundleId: 'com.example.marriageBereauApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZb0b2WNzSlGv9otaME6HyK1rgMzEp48',
    appId: '1:157785319634:ios:8b876ec55092e91a68e50b',
    messagingSenderId: '157785319634',
    projectId: 'marriage-app-71ea3',
    storageBucket: 'marriage-app-71ea3.firebasestorage.app',
    iosBundleId: 'com.example.marriageBereauApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEY3MY4Ngof7ZFWLw4vGbheba44knpDjs',
    appId: '1:157785319634:web:0a862ef94e0ce38068e50b',
    messagingSenderId: '157785319634',
    projectId: 'marriage-app-71ea3',
    authDomain: 'marriage-app-71ea3.firebaseapp.com',
    storageBucket: 'marriage-app-71ea3.firebasestorage.app',
    measurementId: 'G-3XZ2W7C7FD',
  );
}
